spring:
  datasource:
    url: jdbc:mysql://localhost/spring_data
    username: spring
    password: 5pr1ngD4t4
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa.show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect